config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

  root to: 'recruits#index'
  
  resources :teams, only: [:new, :create, :edit, :update] 
  resources :recruits do
    resources :requests do
      member do
        patch 'approve'
        patch 'disapprove'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/home/top.html.erb
<div class="home-top">
  <div class="row mx-1">
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col">
    </div>  
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col">
      <button type="button" class="btn btn-success mt-3 shadow btn-lg">サイトマップ</button>
    </div>
    <div class="col">
      <%= link_to new_team_path do %> 
      <button type="button" class="btn btn-success ml-3 mt-3 shadow btn-lg">チーム登録</button>
      <% end %>
    </div>
    <div class="col"> 
      <button type="button" class="btn btn-success ml-3 mt-3 shadow btn-lg">ログイン</button>
    </div>
    <div class="col">
      <button type="button" class="btn btn-success mt-3 shadow btn-lg ">問合せ</button>
    </div>  
  </div>
  <div class="text-center ">
    <h1 class="display-1 mt-5">Sal.com</h1>
    <h5 class="mt-1">〜シンプルにフットサルしたい人のマッチングサイト〜</h5>
  </div>
  <div class="container">
    <div class="col"> </div>
    <form>
      <div class="row">
        <div class="col">
          <div class="form-group text-white "> <label for="pref">エリア</label> <select class="form-control" id="pref">
                <option value="">都道府県</option>
                <option value="北海道">北海道</option>
                <option value="青森県">青森県</option>
                <option value="宮城県">宮城県</option>
                <option value="岩手県">岩手県</option>
                <option value="秋田県">秋田県</option>
                <option value="山形県">山形県</option>
                <option value="福島県">福島県</option>
                <option value="茨城県">茨城県</option>
                <option value="栃木県">栃木県</option>
                <option value="群馬県">群馬県</option>
                <option value="埼玉県">埼玉県</option>
                <option value="千葉県">千葉県</option>
                <option value="東京都">東京都</option>
                <option value="神奈川県">神奈川県</option>
                <option value="新潟県">新潟県</option>
                <option value="富山県">富山県</option>
                <option value="石川県">石川県</option>
                <option value="福井県">福井県</option>
                <option value="山梨県">山梨県</option>
                <option value="長野県">長野県</option>
                <option value="岐阜県">岐阜県</option>
                <option value="静岡県">静岡県</option>
                <option value="愛知県">愛知県</option>
                <option value="三重県">三重県</option>
                <option value="滋賀県">滋賀県</option>
                <option value="京都府">京都府</option>
                <option value="大阪府">大阪府</option>
                <option value="兵庫県">兵庫県</option>
                <option value="奈良県">奈良県</option>
                <option value="和歌山県">和歌山県</option>
                <option value="鳥取県">鳥取県</option>
                <option value="島根県">島根県</option>
                <option value="岡山県">岡山県</option>
                <option value="広島県">広島県</option>
                <option value="山口県">山口県</option>
                <option value="徳島県">徳島県</option>
                <option value="香川県">香川県</option>
                <option value="愛媛県">愛媛県</option>
                <option value="高知県">高知県</option>
                <option value="福岡県">福岡県</option>
                <option value="佐賀県">佐賀県</option>
                <option value="長崎県">長崎県</option>
                <option value="熊本県">熊本県</option>
                <option value="大分県">大分県</option>
                <option value="宮崎県">宮崎県</option>
                <option value="鹿児島県">鹿児島県</option>
                <option value="沖縄県">沖縄県</option>
              </select> </div>
        </div>
        <div class="col">
          <div class="form-group text-success "> <label class="tema-level">チームレベル</label> <select class="form-control">
                  <option>★★★★★</option>
                  <option>★★★★</option>
                  <option>★★★</option>
                  <option>★★</option>
                  <option>★</option>
                </select> </div>
        </div>
        <div class="col">
          <div class="form-group"> <label for="date">日時</label> <input type="date" class="form-control" id="date"> </div>
        </div>
        <div>
          <div class="col">
            <div class="form-group text-white"> <label for="keyword">キーワード</label> <input type="text" class="form-control" id="keyword"> </div>
          </div>
        </div>
        <div class="col"> <br> <button type="button" class="btn btn-primary mt-2">search</button> </div>
      </div>
    </form>
    <div class="container">
      <div class="row mt-4 col-3 text-white">
        <h2 class="bg-success p-2">対戦相手募集中</h2>
      </div>
      <table class="table table-dark mt-3">
        <thead>
          <tr>
            <th scope="col">チーム名</th>
            <th scope="col">チームレベル</th>
            <th scope="col">エリア</th>
            <th scope="col">日時</th>
            <th scope="col">チーム紹介</th>
            <th scope="col">チーム写真</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>チームA</td>
            <td>★★★★</td>
            <td>東京都品川区</td>
            <td>2020/09/23 19:00 ~ 21:00</td>
            <td>宜しくお願い致します！</td>
            <td></td>
          </tr>
          <tr>
            <td>チームB</td>
            <td>★★★★</td>
            <td>東京都品川区</td>
            <td>2020/09/23 19:00 ~ 21:00</td>
            <td>宜しくお願い致します！</td>
            <td></td>
          </tr>
          <tr>
            <td>チームC</td>
            <td>★★★★</td>
            <td>東京都品川区</td>
            <td>2020/09/23 19:00 ~ 21:00</td>
            <td>宜しくお願い致します！</td>
            <td></td>
          </tr>
          <tr>
            <td>チームD</td>
            <td>★★★★</td>
            <td>東京都品川区</td>
            <td>2020/09/23 19:00 ~ 21:00</td>
            <td>宜しくお願い致します！</td>
            <td></td>
          </tr>
          <% @recruits.each do |recruit| %>
            <tr>
              <td><%= recruit.team.name %></td>
              <td>
                <% recruit.level_type.times do %>
                  ★
                <% end %>
              </td>
              <td><%= recruit.address %></td>
              <td><%= recruit.start_at %> ~ <%= recruit.end_at %></td>
              <td><%= recruit.comment %></td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row">
        <div class="col">
        </div>  
        <div class="col">
        </div>
        <div class="col">
        </div>
        <%= link_to recruits_new_path do %> 
        <button type="button" class="btn btn-warning mt-2 shadow btn-lg">対戦相手募集へ</button>
        <% end %>
      </div>  
    </div>
  </div>
</div>