config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

  root to: 'recruits#index'
  
  resources :teams, only: [:new, :create, :edit, :update] 
  resources :recruits do
    resources :requests do
      member do
        patch 'approve'
        patch 'disapprove'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  belongs_to :team
  has_many :requests
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  def index
    @keyword = params[:keyword].presence || ''
    @pref = params[:pref].presence || '' 
    @date = params[:date].presence || '' 
    @level_type = params[:level_type].presence || '' 
    
    @recruits = Recruit.all
    
    @recruits = @recruits.where('comment like ?',"%#{params[:keyword]}%") if @keyword.present?
    @recruits = @recruits.where(prefecture: params[:pref]) if @pref.present?
    @recruits = @recruits.where(start_at: @date.to_date.beginning_of_day..@date.to_date.end_of_day) if @date.present?
    @recruits = @recruits.where(level_type: params[:level_type]) if @level_type.present?
    
    @recruits = @recruits.order(id: :desc)
    
  end

  def new
    @recruits = Recruit.new
  end
  
  def show
    @recruit = Recruit.find(params[:id])
    @requests = @recruit.requests 
  end
  
  def create
    @recruit = Recruit.new(recruit_params)
    @recruit.team = current_team
    if @recruit.save
      redirect_to root_path
    else
      render:new
    end
  end
    
  private
  
  def recruit_params
    params.require(:recruit).permit(:prefecture, :address, :level_type, :start_at, :end_at, :comment)
  end  
end

app/helpers/recruits_helper.rb
module RecruitsHelper
  def prefectures
    [
      "北海道",
      "青森県",
      "岩手県",
      "宮城県",
      "秋田県",
      "山形県",
      "福島県",
      "茨城県",
      "栃木県",
      "群馬県",
      "埼玉県",
      "千葉県",
      "東京都",
      "神奈川県",
      "新潟県",
      "富山県",
      "石川県",
      "福井県",
      "山梨県",
      "長野県",
      "岐阜県",
      "静岡県",
      "愛知県",
      "三重県",
      "滋賀県",
      "京都府",
      "大阪府",
      "兵庫県",
      "奈良県",
      "和歌山県",
      "鳥取県",
      "島根県",
      "岡山県",
      "広島県",
      "山口県",
      "徳島県",
      "香川県",
      "愛媛県",
      "高知県",
      "福岡県",
      "佐賀県",
      "長崎県",
      "熊本県",
      "大分県",
      "宮崎県",
      "鹿児島県",
      "沖縄県",
    ]
  end
end

app/views/recruits/index.html.erb
<div class="home-top">
  <div class="row mx-1">
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col">
    </div>  
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col">
      <button type="button" class="btn btn-success mt-3 shadow btn-lg">サイトマップ</button>
    </div>
    <div class="col">
      <% if logged_in? %>
        <%= link_to edit_team_path(current_team.id ) do %>
          <button type="button" class="btn btn-success ml-3 mt-3 shadow btn-lg">マイページ</button>
        <% end %>
      <% else %>
        <%= link_to new_team_path do %>
          <button type="button" class="btn btn-success ml-3 mt-3 shadow btn-lg">チーム登録</button>
        <% end %>
      <% end %>
      
    </div>
    <div class="col"> 
      <% if logged_in? %>
        <%= link_to logout_path , method: "delete" do %>
          <button type="button" class="btn btn-success ml-3 mt-3 shadow btn-lg">ログアウト</button>
        <% end %>
      <% else %>
        <%= link_to login_path do %>
          <button type="button" class="btn btn-success ml-3 mt-3 shadow btn-lg">ログイン</button>
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <button type="button" class="btn btn-success mt-3 shadow btn-lg ">問合せ</button>
    </div>  
  </div>
  <div class="row mt-5">
    <div class = "col-9">
    </div>
    <div class="text-right text-light">
      <h3>⭐︎ようこそ<%= current_team&.leader_name %>さん⭐︎</h3>
    </div>
  </div>  
  <div class="text-center ">
    <h1 class="display-1 mt-5">Sal.com</h1>
    <h5 class="mt-1">〜シンプルにフットサルしたい人のマッチングサイト〜</h5>
  </div>
  <div class="container">
    <div class="col"> </div>
    <%= form_tag(root_path, method: 'get') do %>
      <div class="row">
        <div class="col">
          <div class="form-group text-white ">
            <label for="pref">エリア</label>
              <select class="form-control" id="pref" name="pref">
                <option value="">都道府県</option>
                <% prefectures.each do |p| %>
                  <option value="<%= p %>" <%= (@pref == p) ? 'selected' : '' %>><%= p %></option>
                <% end %>
              </select>
          </div>
        </div>
        <div class="col">
          <div class="form-group text-success "> 
            <label class="team-level">チームレベル</label> 
                <select class="form-control" name="level_type" > 
                  <option value=""></option>
                  <option value="5" <%= (@level_type == "5") ? 'selected' : '' %>>★★★★★</option>
                  <option value="4" <%= (@level_type == "4") ? 'selected' : '' %>>★★★★</option>
                  <option value="3" <%= (@level_type == "3") ? 'selected' : '' %>>★★★</option>
                  <option value="2" <%= (@level_type == "2") ? 'selected' : '' %>>★★</option>
                  <option value="1" <%= (@level_type == "1") ? 'selected' : '' %>>★</option>
                </select> </div>
        </div>
        <div class="col">
          <div class="form-group">
            <label for="date">日時</label>
            <input type="date" class="form-control" id="date" name="date" value=<%= @date %>>
          </div>
        </div>
            <div>
              <div class="col">
                <div class="form-group text-white">
                  <label for="keyword">キーワード</label>
                  <%= text_field_tag :keyword, @keyword, { class: 'form-control' }%>
                </div>
              </div>
            </div>
          <div class="col"> <br>
        <button type="submit" class="btn btn-primary mt-2">search</button></div>
      </div>
    <% end %>
    <div class="container">
      <div class="row mt-4 col-3 text-white">
        <h2 class="bg-success p-2">対戦相手募集中</h2>
      </div>
      <table class="table table-dark mt-3">
        <thead>
          <tr>
            <th scope="col">チーム名</th>
            <th scope="col">チームレベル</th>
            <th scope="col">場所</th>
            <th scope="col">日時</th>
            <th scope="col">チーム紹介</th>
            <th scope="col">チーム写真</th>
          </tr>
        </thead>
        <tbody>
          <% @recruits.each do |recruit| %>
            <tr>
              <td><%= link_to recruit_path(recruit) do %><%= recruit.team.name %><% end %>
              </td>
              <td>
                <% recruit.level_type.times do %>★<% end %>
              </td>
              <td>
                <%= recruit.prefecture %><%= recruit.address %>
              </td>
              <td>
                <%= recruit.start_at.strftime("%Y/%m/%d %H:%M") %> ~ <%= recruit.end_at.strftime("%H:%M") %>
              </td>
              <td>
                <%= recruit.comment %>
                </td>
              <td>
                <%= image_tag(recruit.team.image_url, width: '100px') if recruit.team.image? %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row">
        <div class="col">
        </div>  
        <div class="col">
        </div>
        <div class="col">
        </div>
        <%= link_to new_recruit_path do %> 
        <button type="button" class="btn btn-warning mt-2 shadow btn-lg">対戦相手募集へ</button>
        <% end %>
      </div>  
    </div>
  </div>
</div>

app/views/recruits/new.html.erb
<div class="recruits-new">
  <div class="row">
    <div class="col mt-4">
      <%= link_to root_path do %> 
      <button class="float-right mr-3 bg-info btn btn-info">TOPに戻る</button>
      <% end %>
    </div>
  </div>
    <div class="text-center mx-auto bg-primary py-2 shadow col-3 rounded mt-5">
      <h1 class="pt-2">対戦相手募集</h1>
    </div>
    <div class="container">
      <%= form_for(@recruits) do |f| %>  
     
        <div class="form-group h4 col-7 p-0 text-white ">
          <label for="pref">都道府県</label> 
            <select class="form-control form-control-lg" id="pref" name="recruit[prefecture]">
              <option value="">都道府県</option>
                <% prefectures.each do |p| %>
                  <option value="<%= p %>"><%= p %></option>
                <% end %>
            </select> 
        </div>
        <div class="form-group h4 col-7 p-0 text-white">
            <label for="exampleFormControlInput1">エリア</label>
            <%= f.text_field :address, class: 'form-control form-control-lg', placeholder: "エリア" %>        
        </div>
        <div class="form-group h4 col-7 p-0 text-white">
            <label for="exampleFormControlInput1">チームレベル</label>
          <select class="form-control form-control-lg" id="pref" name="recruit[level_type]">
              <option value="1">★</option>
              <option value="2">★★</option>
              <option value="3">★★★</option>
              <option value="4">★★★★</option>
              <option value="5">★★★★★</option>
            </select>
        </div>
        <div class="form-group h4 col-7 p-0 text-white">
          <label for="exampleFormControlInput1">開始日時</label>
          <input type="datetime-local" class="form-control form-control-lg" id="exampleFormControlInput1" name="recruit[start_at]">
        </div>
        <div class="form-group h4 col-7 p-0 text-white">
          <label for="exampleFormControlInput1">終了日時</label>
          <input type="datetime-local" class="form-control form-control-lg" id="exampleFormControlInput1" name="recruit[end_at]">
        </div>
        <div class="form-group h4 col-10 p-0 text-white">
          <label for="exampleFormControlTextarea1">一言コメント</label>
          <textarea class="form-control form-control-lg" id="exampleFormControlTextarea1" rows="4" name="recruit[comment]"></textarea>
        </div>
        <div class="col">
        <button type="submit-col-7" class="float-right btn btn-primary col-2 mt-3 l-3">登録へ</button>
        </div>
      <% end %>
  </div>  
</div>    
    

app/views/recruits/show.html.erb
<div class="teams-new">
  <div class="row">
    <div class="col mt-4">
      <%= link_to root_path do %> 
      <button class="float-right mr-3 bg-info btn btn-info">TOPに戻る</button>
      <% end %>
    </div>
  </div>
  <div class="text-center mx-auto bg-primary py-2 shadow col-3 rounded mt-4">
    <h1 class="pt-2">対戦相手DATA</h1>
  </div>
    <div class="container">
      <div class="row">
        <div class="col-md-5 mt-4 mr-5 text-white">
          <h2 class="p-3">・チーム名</h2>
            <h4 class="pl-5 mb-5"><%= @recruit.team.name %></h4>
          <h2 class="p-3">・日時</h2>
            <p class="pl-5 mb-5"><%= @recruit.start_at.strftime("%Y/%m/%d %H:%M") %> ~ <%= @recruit.end_at.strftime("%H:%M")%></p>
          <h2 class="p-3">・エリア</h2>
            <p class="pl-5 mb-5"><%= @recruit.prefecture %><%= @recruit.address %></p>
          <h2 class="p-3">・チームレベル</h2>
            <p class="pl-5 mb-5"><% @recruit.level_type.times do %>★<% end %></p>
          <h2 class="p-3">・コメント</h2>
            <p class="pl-5 mb-5"><%= @recruit.comment %></p>
        </div>
        <div class="col-md-5 mt-5 ">
          <%= image_tag(@recruit.team.image_url, width:'300px') if @recruit.team.image? %>
        </div>  
      </div> 
    </div>
    <div class="row">
        <div class="col-4">
        </div>  
        <div class="col-4 text-center">
          <% if current_team.present? && current_team.requests.find_by(recruit: @recruit).present? %>
            <div class="alert alert-danger text-center" role="alert">応募済み</div>
          <% elsif current_team.present? && current_team != @recruit.team %>
            <%= link_to recruit_requests_path(@recruit), method: 'post' do %>
              <button type="submit" class="btn btn-primary col-md-4 mt-3 l-3">応募する</button>
            <% end %>
          <% end %>
        </div>
        <div class="col-4">
        </div>
    </div>
    <div class ="container">
      <div class ="row">
        <h2 class ="col-6 text-center mt-4 bg-info text-white">このチームに応募しているチーム</h2>
      </div> 
      <table class="table mt-4 table-secondary">
        <thead class ="thead-secondary">
          <tr>
            <th scope ="col">チーム名</th>
            <th scope ="col">レベル</th>
            <th scope ="col">ステータス</th>
            <% if @recruit.team == current_team %>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @requests.each do |request| %>
            <tr>
              <td>
                <%= request.team.name %>
              </td>
              <td>
                <%= request.team.level_type %>
              </td>
              <td>
                <%= request.display_status %>
              </td>
              <% if @recruit.team == current_team %>
                <td class = "text-center">
                  <% if request.unconfirmed? %>
                    <%= link_to approve_recruit_request_path(@recruit, request), method: 'patch' do %>
                      <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">承認</button>
                    <% end %>
                    <%= link_to disapprove_recruit_request_path(@recruit, request), method: 'patch' do %>
                      <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">拒否</button>
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            </tr>  
          <% end %>
        </tbody>
      </table>
    </div>
  </div>